### PR TITLE
.get()

### PR DESCRIPTION
**Pull request by denis-sokolov**

### CODE REVIEW

**Comment by mwilliamson** [comment]
I'm a bit torn on this one: the purist in me says that you're better off using the safer methods, such as `valueOrElse()`, so use of `get()` should be discouraged in most cases. Perhaps renaming this to `valueOrError()` or similar would make that clearer, assuming that you agree with the original point?

**Comment by denis-sokolov** [comment]
I tend to have situations where I know for sure the option is Some due to external factors. Without `.get` I am forced to either use `.valueOrElse(function(){ throw new Error(); });`, which is awfully long, or I do `.valueOrElse(null)` and allow the possibility of an obscure null property access error later, which seems dirty. `.get` then would clearly communicate something similar to `assert(foo instanceof Some)`.

`.valueOrError` would achieve my goal as well, and it's just bikeshedding, but consider some reasons to use `.get`. Primarily, consistency. `data.maybe` [uses `.get`](http://docs.folktalejs.org/en/latest/api/data/maybe/Maybe.html#Maybe.prototype.get).  Scala [uses `.get`](http://www.scala-lang.org/api/current/index.html#scala.Option@get:A). Unfortunately, this is where my experience ends and I'm not sure if there are more examples of `.get` method.
Secondly, I believe `.get` as a nice name is more likely to have a positive effect on developers who like `null`s. This way they can use options as `null` references at the cost of six extra characters, which is easy. A clunky name like `.valueOrError` does communicate the meaning of the function slightly better, and it does discourage its use, but it also reads as something you wouldn't use too often.

**Comment by mwilliamson** [comment]
> `.valueOrError` would achieve my goal as well, and it's just bikeshedding, but consider some reasons to use `.get`.

I think this is more important than bikeshedding: the way the API is designed, down to the names, will influence the way it gets used, which is really what the option type is all about (since it doesn't implement any actually interesting functionality).

> Primarily, consistency. `data.maybe` [uses `.get`](http://docs.folktalejs.org/en/latest/api/data/maybe/Maybe.html#Maybe.prototype.get).  Scala [uses `.get`](http://www.scala-lang.org/api/current/index.html#scala.Option@get:A). Unfortunately, this is where my experience ends and I'm not sure if there are more examples of `.get` method.

F# uses the `Value` property for its option type, although it also has a `get` function (not method). OCaml similarly has a `get` function. SML seems to have a `valOf` function that does the same job, while Haskell's equivalent seems to be `fromJust` (which at least has some indication that it has the expectation that the value is `Just _` rather than `Nothing`).

> Secondly, I believe `.get` as a nice name is more likely to have a positive effect on developers who like `null`s. This way they can use options as `null` references at the cost of six extra characters, which is easy. A clunky name like `.valueOrError` does communicate the meaning of the function slightly better, and it does discourage its use, but it also reads as something you wouldn't use too often.

But isn't that the point? If you're regularly using the function (whatever it's called), then that suggests that the structure of your program is slightly off: the value I get from using option types is to make it clearer when a `none` value is possible, and force it to be dealt with.

I'll think a bit more about the name.

**Comment by denis-sokolov** [comment]
> But isn't that the point? If you're regularly using the function (whatever it's called), then that suggests that the structure of your program is slightly off: the value I get from using option types is to make it clearer when a `none` value is possible, and force it to be dealt with.

Yes. Kind of. I mean, I know the advantages of options and problems of `null`, that's why I'm using options. But this also means that I don't care whatsoever about the educational value of the name `.valueOrError`, I know I shouldn't use it too much, and when I need to, I value convenience and shortness of `.get`.

There is educational value for people who are only starting out to use options, but I'm not sure whether that provides enough value.

Finally there's the use case of a boundary between an Option world and a `null` world.
The `null` world developers might be less grumpy about `.get` as opposed to `.valueOrError`.

**Comment by denis-sokolov** [comment]
As to explain why do I often end up in situations where my options can't be `none`: in certain async situations, I have a mutable reference that is sometimes `Some` and sometimes `None`. Often I end up in a situation where I have just mutated the reference into `Some` and to do a bit more with it. Because of the single-threaded JavaScript semantics, I know for sure the reference can't be `None` until I give away the event loop. `.get()` is really nice for such scenarios.

**Comment by mwilliamson** [comment]
Hmm, good point that anybody who's using this already knows the benefits.

In which case, the name should probably be `value()` rather than `get()` for consistency with `valueOrElse()` -- how does that sound to you?

**Comment by denis-sokolov** [comment]
I suppose the internal consistency makes a lot of sense, yes.

**Pull request merged**
